// <auto-generated />
using System;
using Infrastructure.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    [Migration("20211116185009_SetupInicial")]
    partial class SetupInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.ImportDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MinimalDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalDeliveryItens")
                        .HasColumnType("float");

                    b.Property<long>("TotalItens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ImportDeliveries");
                });

            modelBuilder.Entity("Domain.Entities.ImportDeliveryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImportDeliveryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportDeliveryId");

                    b.ToTable("ImportDeliveryItens");
                });

            modelBuilder.Entity("Domain.Entities.ImportDeliveryItem", b =>
                {
                    b.HasOne("Domain.Entities.ImportDelivery", "ImportDelivery")
                        .WithMany("ImportDeliveryItens")
                        .HasForeignKey("ImportDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportDelivery");
                });

            modelBuilder.Entity("Domain.Entities.ImportDelivery", b =>
                {
                    b.Navigation("ImportDeliveryItens");
                });
#pragma warning restore 612, 618
        }
    }
}
